# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 2020_05_27_152031) do

  create_table "active_storage_attachments", force: :cascade do |t|
    t.string "name", null: false
    t.string "record_type", null: false
    t.integer "record_id", null: false
    t.integer "blob_id", null: false
    t.datetime "created_at", null: false
    t.index ["blob_id"], name: "index_active_storage_attachments_on_blob_id"
    t.index ["record_type", "record_id", "name", "blob_id"], name: "index_active_storage_attachments_uniqueness", unique: true
  end

  create_table "active_storage_blobs", force: :cascade do |t|
    t.string "key", null: false
    t.string "filename", null: false
    t.string "content_type"
    t.text "metadata"
    t.bigint "byte_size", null: false
    t.string "checksum", null: false
    t.datetime "created_at", null: false
    t.index ["key"], name: "index_active_storage_blobs_on_key", unique: true
  end

  create_table "form1s", force: :cascade do |t|
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "formType"
    t.string "type1"
    t.string "eFullname"
    t.string "aFullname"
    t.string "uni"
    t.string "dep"
    t.string "country"
    t.string "email"
    t.string "wPhone"
    t.string "hPhone"
    t.string "pPhone"
    t.string "bDate"
    t.string "bUni"
    t.string "btime"
    t.string "bsub"
    t.string "mDate"
    t.string "mUni"
    t.string "mtime"
    t.string "msub"
    t.string "dDate"
    t.string "dUni"
    t.string "dtime"
    t.string "dsub"
    t.string "aName"
    t.string "aSub"
    t.string "aFrom"
    t.string "aTime"
    t.string "aName1"
    t.string "aSub1"
    t.string "aFrom1"
    t.string "aTime1"
    t.string "pHeadline"
    t.string "pRate"
    t.string "pName"
    t.string "pISSN"
    t.string "pYear"
    t.string "pHeadline1"
    t.string "pRate1"
    t.string "pName1"
    t.string "pISSN1"
    t.string "pYear1"
    t.string "pHeadline2"
    t.string "pRate2"
    t.string "pName2"
    t.string "pISSN2"
    t.string "pYear2"
    t.string "pHeadline3"
    t.string "pRate3"
    t.string "pName3"
    t.string "pISSN3"
    t.string "pYear3"
    t.string "pHeadline4"
    t.string "pRate4"
    t.string "pName4"
    t.string "pISSN4"
    t.string "pYear4"
    t.string "pHeadline5"
    t.string "pRate5"
    t.string "pName5"
    t.string "pISSN5"
    t.string "pYear5"
    t.string "pHeadline6"
    t.string "pRate6"
    t.string "pName6"
    t.string "pISSN6"
    t.string "pYear6"
    t.string "pHeadline7"
    t.string "pRate7"
    t.string "pName7"
    t.string "pISSN7"
    t.string "pYear7"
    t.string "bHeadline"
    t.string "bRate"
    t.string "bNum"
    t.string "bAuthor"
    t.string "bYear"
    t.string "bHeadline1"
    t.string "bRate1"
    t.string "bNum1"
    t.string "bAuthor1"
    t.string "bYear1"
    t.string "bHeadline2"
    t.string "bRate2"
    t.string "bNum2"
    t.string "bAuthor2"
    t.string "bYear2"
    t.string "bHeadline3"
    t.string "bRate3"
    t.string "bNum3"
    t.string "bAuthor3"
    t.string "bYear3"
    t.string "bHeadline4"
    t.string "bRate4"
    t.string "bNum4"
    t.string "bAuthor4"
    t.string "bYear4"
    t.string "cHeadline"
    t.string "cSolo"
    t.string "cRate"
    t.string "cCharge"
    t.string "cFrom"
    t.string "cDate"
    t.string "cNUm"
    t.string "cHeadline1"
    t.string "cSolo1"
    t.string "cRate1"
    t.string "cCharge1"
    t.string "cFrom1"
    t.string "cDate1"
    t.string "cNUm1"
    t.string "sName"
    t.string "sType"
    t.string "sTime"
    t.string "sName1"
    t.string "sType1"
    t.string "sTime1"
    t.string "sName2"
    t.string "sType2"
    t.string "sTime2"
    t.string "supHeadline"
    t.string "supYear"
    t.string "supTime"
    t.string "supType"
    t.string "supAmount"
    t.string "supFrom"
    t.string "supHeadline1"
    t.string "supYear1"
    t.string "supTime1"
    t.string "supType1"
    t.string "supAmount1"
    t.string "supFrom1"
    t.string "supHeadline2"
    t.string "supYear2"
    t.string "supTime2"
    t.string "supType2"
    t.string "supAmount2"
    t.string "supFrom2"
    t.string "supHeadline3"
    t.string "supYear3"
    t.string "supTime3"
    t.string "supType3"
    t.string "supAmount3"
    t.string "supFrom3"
  end

  create_table "form2s", force: :cascade do |t|
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "formType"
    t.string "type1"
    t.string "eFullname"
    t.string "aFullname"
    t.string "uni"
    t.string "dep"
    t.string "country"
    t.string "email"
    t.string "wPhone"
    t.string "hPhone"
    t.string "pPhone"
    t.string "bDate"
    t.string "bUni"
    t.string "bGpa"
    t.string "btime"
    t.string "bsub"
    t.string "mDate"
    t.string "mUni"
    t.string "mGpa"
    t.string "mtime"
    t.string "msub"
    t.string "dDate"
    t.string "dUni"
    t.string "dGpa"
    t.string "dtime"
    t.string "dsub"
    t.string "rHeadline"
    t.string "rSolo"
    t.string "rPlace"
    t.string "rCharge"
    t.string "rCover"
    t.string "rRate"
    t.string "rYear"
    t.string "rHeadline1"
    t.string "rSolo1"
    t.string "rPlace1"
    t.string "rCharge1"
    t.string "rCover1"
    t.string "rRate1"
    t.string "rYear1"
    t.string "rHeadline2"
    t.string "rSolo2"
    t.string "rPlace2"
    t.string "rCharge2"
    t.string "rCover2"
    t.string "rRate2"
    t.string "rYear2"
    t.string "cHeadline"
    t.string "cSolo"
    t.string "cRate"
    t.string "cCharge"
    t.string "cFrom"
    t.string "cDate"
    t.string "cNum"
    t.string "cHeadline1"
    t.string "cSolo1"
    t.string "cRate1"
    t.string "cCharge1"
    t.string "cFrom1"
    t.string "cDate1"
    t.string "cNum1"
    t.string "cHeadline2"
    t.string "cSolo2"
    t.string "cRate2"
    t.string "cCharge2"
    t.string "cFrom2"
    t.string "cDate2"
    t.string "cNum2"
  end

  create_table "form3s", force: :cascade do |t|
    t.string "formType"
    t.string "number"
    t.string "info"
    t.string "name"
    t.string "degree"
    t.string "time"
    t.string "reward"
    t.string "mainB"
    t.string "jobN"
    t.string "date"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "form4s", force: :cascade do |t|
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "formType"
    t.string "from"
    t.string "to"
    t.string "amount"
    t.string "number"
    t.string "info"
    t.string "r1"
    t.string "r2"
    t.string "r3"
    t.string "mR"
    t.string "jNum"
    t.string "date"
  end

  create_table "form5s", force: :cascade do |t|
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "formType"
    t.string "number"
    t.string "rNumber"
    t.string "date"
    t.string "address"
    t.string "info"
    t.string "mR"
    t.string "eR"
    t.string "aDate"
    t.string "sDate"
    t.string "fDate"
    t.string "amount"
    t.string "spent"
    t.string "s1"
    t.string "s2"
    t.string "s3"
    t.string "s4"
    t.string "s5"
    t.string "s6"
    t.string "l1"
    t.string "l2"
    t.string "l3"
    t.string "l4"
    t.string "l5"
    t.string "l6"
    t.string "timeLeft"
    t.string "infoOn"
    t.string "infoNotStarted"
    t.string "infoStopped"
    t.string "mName"
    t.string "mDep"
    t.string "mSection"
  end

  create_table "form6s", force: :cascade do |t|
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "formType"
    t.string "number"
    t.string "info"
    t.string "fNum"
    t.string "fDate"
    t.string "fCompany"
    t.string "fAmount"
    t.string "fNum1"
    t.string "fDate1"
    t.string "fCompany1"
    t.string "fAmount1"
    t.string "fNum2"
    t.string "fDate2"
    t.string "fCompany2"
    t.string "fAmount2"
    t.string "fNum3"
    t.string "fDate3"
    t.string "fCompany3"
    t.string "fAmount3"
    t.string "fNum4"
    t.string "fDate4"
    t.string "fCompany4"
    t.string "fAmount4"
    t.string "mR"
    t.string "jNum"
    t.string "date"
  end

  create_table "form7s", force: :cascade do |t|
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "formType"
    t.string "amount"
    t.string "name"
    t.string "jNum"
    t.string "from"
    t.string "to"
    t.string "rName"
    t.string "fWork"
    t.string "Date"
    t.string "notes"
  end

  create_table "form8s", force: :cascade do |t|
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "formType"
    t.string "amount"
    t.string "number"
    t.string "from"
    t.string "rNum"
    t.string "mawsoom"
    t.string "mR"
    t.string "jNum"
    t.string "date"
  end

  create_table "form9s", force: :cascade do |t|
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "formType"
    t.string "amount"
    t.string "number"
    t.string "mawsoom"
    t.string "bNum"
    t.string "bDate"
    t.string "bCompany"
    t.string "bAmount"
    t.string "bNum1"
    t.string "bDate1"
    t.string "bCompany1"
    t.string "bAmount1"
    t.string "bNum2"
    t.string "bDate2"
    t.string "bCompany2"
    t.string "bAmount2"
    t.string "bNum3"
    t.string "bDate3"
    t.string "bCompany3"
    t.string "bAmount3"
    t.string "bNum4"
    t.string "bDate4"
    t.string "bCompany4"
    t.string "bAmount4"
    t.string "mR"
    t.string "jNum"
    t.string "date"
  end

  create_table "users", force: :cascade do |t|
    t.string "username"
    t.string "password_digest"
    t.string "firstname"
    t.string "lastname"
    t.boolean "admin"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

end
