class CreateForm1 < ActiveRecord::Migration[5.2]
  def change
    create_table :form1s do |t|
      t.timestamps
      t.string :formType
      t.string :type1
      t.string :eFullname
      t.string :aFullname
      t.string :uni
      t.string :dep
      t.string :country
      t.string :email
      t.string :wPhone
      t.string :hPhone
      t.string :pPhone
      t.string :bDate
      t.string :bUni
      t.string :btime
      t.string :bsub
      t.string :mDate
      t.string :mUni
      t.string :mtime
      t.string :msub
      t.string :dDate
      t.string :dUni
      t.string :dtime
      t.string :dsub
      t.string :aName
      t.string :aSub
      t.string :aFrom
      t.string :aTime
      t.string :aName1
      t.string :aSub1
      t.string :aFrom1
      t.string :aTime1
      t.string :pHeadline
      t.string :pRate
      t.string :pName
      t.string :pISSN
      t.string :pYear
      t.string :pHeadline1
      t.string :pRate1
      t.string :pName1
      t.string :pISSN1
      t.string :pYear1
      t.string :pHeadline2
      t.string :pRate2
      t.string :pName2
      t.string :pISSN2
      t.string :pYear2


      t.string :pHeadline3
      t.string :pRate3
      t.string :pName3
      t.string :pISSN3
      t.string :pYear3
      t.string :pHeadline4
      t.string :pRate4
      t.string :pName4
      t.string :pISSN4
      t.string :pYear4
      t.string :pHeadline5
      t.string :pRate5
      t.string :pName5
      t.string :pISSN5
      t.string :pYear5

      t.string :pHeadline6
      t.string :pRate6
      t.string :pName6
      t.string :pISSN6
      t.string :pYear6
      t.string :pHeadline7
      t.string :pRate7
      t.string :pName7
      t.string :pISSN7
      t.string :pYear7

      t.string :bHeadline
      t.string :bRate
      t.string :bNum
      t.string :bAuthor
      t.string :bYear
      t.string :bHeadline1
      t.string :bRate1
      t.string :bNum1
      t.string :bAuthor1
      t.string :bYear1
      t.string :bHeadline2
      t.string :bRate2
      t.string :bNum2
      t.string :bAuthor2
      t.string :bYear2

      t.string :bHeadline3
      t.string :bRate3
      t.string :bNum3
      t.string :bAuthor3
      t.string :bYear3
      t.string :bHeadline4
      t.string :bRate4
      t.string :bNum4
      t.string :bAuthor4
      t.string :bYear4

      t.string :cHeadline
      t.string :cSolo
      t.string :cRate
      t.string :cCharge
      t.string :cFrom
      t.string :cDate
      t.string :cNUm
      t.string :cHeadline1
      t.string :cSolo1
      t.string :cRate1
      t.string :cCharge1
      t.string :cFrom1
      t.string :cDate1
      t.string :cNUm1

      t.string :sName
      t.string :sType
      t.string :sTime
      t.string :sName1
      t.string :sType1
      t.string :sTime1
      t.string :sName2
      t.string :sType2
      t.string :sTime2

      t.string :supHeadline
      t.string :supYear
      t.string :supTime
      t.string :supType
      t.string :supAmount
      t.string :supFrom
      t.string :supHeadline1
      t.string :supYear1
      t.string :supTime1
      t.string :supType1
      t.string :supAmount1
      t.string :supFrom1
      t.string :supHeadline2
      t.string :supYear2
      t.string :supTime2
      t.string :supType2
      t.string :supAmount2
      t.string :supFrom2
      t.string :supHeadline3
      t.string :supYear3
      t.string :supTime3
      t.string :supType3
      t.string :supAmount3
      t.string :supFrom3
    end
  end
end
